spring:
  application:
    name: expense-manager

  datasource:
    url: jdbc:mysql://localhost:3306/expense_manager
    username: root
    password: Raj@123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080