server:
  port: ${PORT:8080}

spring:
  application:
    name: expense-manager
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  datasource:
    url: jdbc:mysql://localhost:3306/expense_manager
    username: root
    password: Raj@123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: x<S&SiM6Fv:rO23j9(,J{ybK!vzlN(v_
  expiration: 36000000

logging:
  level:
    root: INFO
    com.rajendra.expensemanager: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"